<?php

/**
 * @file
 * Contains placements.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function placements_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the placements module.
    case 'help.page.placements':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Placement Content Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function placements_theme() {
  return [
    'placements' => [
      'render element' => 'children',
    ],
  ];
}
